/**
 * Dados só da tela "Demonstração (sem dados reais)".
 * São placeholders neutros — este repo é base para clonar por cliente, não um CRM de um nicho.
 */
import { ETAPAS_CRM, composeInteresse } from "@/lib/constants";

export type PreviewRow = Record<string, unknown>;
export type PreviewDb = Record<string, PreviewRow[]>;

function id(n: number) {
  return `00000000-0000-4000-8000-${String(n).padStart(12, "0")}`;
}

function iso(daysFromNow: number, hours = 10) {
  const d = new Date();
  d.setDate(d.getDate() + daysFromNow);
  d.setHours(hours, 0, 0, 0);
  return d.toISOString();
}

const agora = new Date().toISOString();

const etapas = ETAPAS_CRM.map((e, i) => ({
  id: id(10 + i),
  nome: e.nome,
  cor: e.cor,
  tipo: e.tipo,
  ordem: i + 1,
  criado_em: iso(-30),
}));

const etapa = (nome: string) => etapas.find((e) => e.nome === nome)!.id;

const contatos = [
  {
    id: id(101),
    nome: "Ana Exemplo",
    email: "ana@exemplo.local",
    telefone: "11987654321",
    nome_estabelecimento: "Empresa exemplo A",
    anos_operacao: 8,
    segmento: "Segmento A",
    observacoes: "Contato fictício da demonstração.",
    observacoes_internas: null,
    metadados: {},
    criado_em: iso(-18),
    atualizado_em: agora,
  },
  {
    id: id(102),
    nome: "Bruno Exemplo",
    email: "bruno@exemplo.local",
    telefone: "21999887766",
    nome_estabelecimento: "Empresa exemplo B",
    anos_operacao: 12,
    segmento: "Segmento B",
    observacoes: null,
    observacoes_internas: null,
    metadados: {},
    criado_em: iso(-14),
    atualizado_em: agora,
  },
  {
    id: id(103),
    nome: "Carla Exemplo",
    email: "carla@exemplo.local",
    telefone: "31988776655",
    nome_estabelecimento: "Empresa exemplo C",
    anos_operacao: 5,
    segmento: "Segmento C",
    observacoes: null,
    observacoes_internas: null,
    metadados: {},
    criado_em: iso(-9),
    atualizado_em: agora,
  },
  {
    id: id(104),
    nome: "Diego Exemplo",
    email: "diego@exemplo.local",
    telefone: "51977665544",
    nome_estabelecimento: "Empresa exemplo D",
    anos_operacao: 20,
    segmento: "Segmento A",
    observacoes: null,
    observacoes_internas: null,
    metadados: {},
    criado_em: iso(-6),
    atualizado_em: agora,
  },
  {
    id: id(105),
    nome: "Elisa Exemplo",
    email: "elisa@exemplo.local",
    telefone: "11966554433",
    nome_estabelecimento: "Empresa exemplo E",
    anos_operacao: 3,
    segmento: "Segmento B",
    observacoes: null,
    observacoes_internas: null,
    metadados: {},
    criado_em: iso(-2),
    atualizado_em: agora,
  },
  {
    id: id(106),
    nome: "Fábio Exemplo",
    email: "fabio@exemplo.local",
    telefone: "85955443322",
    nome_estabelecimento: "Empresa exemplo F",
    anos_operacao: 7,
    segmento: "Segmento C",
    observacoes: null,
    observacoes_internas: null,
    metadados: {},
    criado_em: iso(0),
    atualizado_em: agora,
  },
];

function opp(n: number, extra: PreviewRow): PreviewRow {
  const contato = contatos.find((c) => c.id === extra.contato_id) ?? contatos[0];
  return {
    id: id(n),
    titulo: extra.titulo,
    interesse: extra.interesse,
    nome_estabelecimento: contato.nome_estabelecimento,
    anos_operacao: contato.anos_operacao,
    descricao: extra.descricao ?? null,
    origem: extra.origem ?? "manual",
    etapa_id: extra.etapa_id,
    contato_id: contato.id,
    valor: extra.valor ?? null,
    data_visita: extra.data_visita ?? null,
    data_fechamento: extra.data_fechamento ?? null,
    motivo_perda: extra.motivo_perda ?? null,
    google_event_id: null,
    observacoes: extra.observacoes ?? null,
    responsavel: extra.responsavel ?? "Comercial",
    metadados: {},
    criado_em: extra.criado_em ?? iso(-4),
    atualizado_em: agora,
  };
}

const oportunidades = [
  opp(201, {
    contato_id: id(106),
    titulo: "Empresa exemplo F — lead novo",
    interesse: composeInteresse("Segmento C", "Pequena"),
    origem: "formulario_site",
    etapa_id: etapa("Lead novo"),
    criado_em: iso(0),
  }),
  opp(202, {
    contato_id: id(105),
    titulo: "Empresa exemplo E — qualificação",
    interesse: composeInteresse("Segmento B", "Pequena"),
    origem: "instagram",
    etapa_id: etapa("Qualificação"),
    criado_em: iso(-2),
  }),
  opp(203, {
    contato_id: id(103),
    titulo: "Empresa exemplo C — atendimento",
    interesse: composeInteresse("Segmento C", "Média"),
    origem: "whatsapp",
    etapa_id: etapa("Atendimento humano"),
    criado_em: iso(-5),
  }),
  opp(204, {
    contato_id: id(101),
    titulo: "Empresa exemplo A — demo agendada",
    interesse: composeInteresse("Segmento A", "Média"),
    origem: "indicacao",
    etapa_id: etapa("Demo agendada"),
    data_visita: iso(3, 14),
    criado_em: iso(-8),
  }),
  opp(205, {
    contato_id: id(102),
    titulo: "Empresa exemplo B — demo realizada",
    interesse: composeInteresse("Segmento B", "Média"),
    origem: "meta_ads",
    etapa_id: etapa("Demo realizada"),
    data_visita: iso(-1, 11),
    criado_em: iso(-11),
  }),
  opp(206, {
    contato_id: id(104),
    titulo: "Empresa exemplo D — proposta",
    interesse: composeInteresse("Segmento A", "Grande"),
    origem: "manual",
    etapa_id: etapa("Proposta enviada"),
    valor: 48000,
    criado_em: iso(-13),
  }),
  opp(207, {
    contato_id: id(101),
    titulo: "Empresa exemplo A — negociação",
    interesse: composeInteresse("Segmento A", "Média"),
    origem: "whatsapp",
    etapa_id: etapa("Negociação"),
    valor: 22000,
    criado_em: iso(-16),
  }),
  opp(208, {
    contato_id: id(103),
    titulo: "Empresa exemplo C — follow-up",
    interesse: composeInteresse("Segmento C", "Média"),
    origem: "instagram",
    etapa_id: etapa("Follow-up / Remarketing"),
    criado_em: iso(-20),
  }),
  opp(209, {
    contato_id: id(102),
    titulo: "Empresa exemplo B — ganho",
    interesse: composeInteresse("Segmento B", "Média"),
    origem: "indicacao",
    etapa_id: etapa("Ganho"),
    valor: 36000,
    data_fechamento: iso(-3),
    criado_em: iso(-28),
  }),
  opp(210, {
    contato_id: id(104),
    titulo: "Empresa exemplo D — perdido",
    interesse: composeInteresse("Segmento A", "Grande"),
    origem: "outro",
    etapa_id: etapa("Perdido"),
    motivo_perda: "Não é o momento",
    criado_em: iso(-22),
  }),
];

const etiquetas = [
  { id: id(701), nome: "Quente", cor: "#ef4444", criado_em: iso(-30) },
  { id: id(702), nome: "Indicação", cor: "#8b5cf6", criado_em: iso(-30) },
  { id: id(703), nome: "Prioridade", cor: "#0ea5e9", criado_em: iso(-30) },
];

const contato_etiquetas = [
  { contato_id: id(101), etiqueta_id: id(701) },
  { contato_id: id(101), etiqueta_id: id(702) },
  { contato_id: id(104), etiqueta_id: id(703) },
  { contato_id: id(106), etiqueta_id: id(701) },
];

const tarefas = [
  {
    id: id(301),
    titulo: "Ligar para Ana Exemplo",
    descricao: "Confirmar horário da demo.",
    status: "aberta",
    prioridade: "alta",
    due_date: iso(-1, 9),
    contato_id: id(101),
    oportunidade_id: id(204),
    atribuido_para: "Comercial",
    criado_por: id(1),
    concluida_em: null,
    criado_em: iso(-3),
    atualizado_em: agora,
  },
  {
    id: id(302),
    titulo: "Enviar proposta Empresa exemplo D",
    descricao: null,
    status: "em_andamento",
    prioridade: "media",
    due_date: iso(1, 16),
    contato_id: id(104),
    oportunidade_id: id(206),
    atribuido_para: "Comercial",
    criado_por: id(1),
    concluida_em: null,
    criado_em: iso(-2),
    atualizado_em: agora,
  },
  {
    id: id(303),
    titulo: "Follow-up Empresa exemplo C",
    descricao: null,
    status: "aberta",
    prioridade: "baixa",
    due_date: iso(4, 10),
    contato_id: id(103),
    oportunidade_id: id(208),
    atribuido_para: "CS",
    criado_por: id(1),
    concluida_em: null,
    criado_em: iso(-1),
    atualizado_em: agora,
  },
  {
    id: id(304),
    titulo: "Assinar contrato Empresa exemplo B",
    descricao: null,
    status: "concluida",
    prioridade: "urgente",
    due_date: iso(-4, 15),
    contato_id: id(102),
    oportunidade_id: id(209),
    atribuido_para: "Comercial",
    criado_por: id(1),
    concluida_em: iso(-3),
    criado_em: iso(-10),
    atualizado_em: agora,
  },
];

const calendario_eventos = [
  {
    id: id(401),
    google_event_id: null,
    titulo: "Demo Empresa exemplo A",
    descricao: "Reunião de demonstração (dados fictícios).",
    inicio: iso(3, 14),
    fim: iso(3, 15),
    local: "Online",
    contato_id: id(101),
    oportunidade_id: id(204),
    criado_por: id(1),
    sincronizado_em: null,
    criado_em: iso(-8),
    atualizado_em: agora,
  },
  {
    id: id(402),
    google_event_id: null,
    titulo: "Proposta Empresa exemplo D",
    descricao: null,
    inicio: iso(1, 16),
    fim: iso(1, 17),
    local: "Online",
    contato_id: id(104),
    oportunidade_id: id(206),
    criado_por: id(1),
    sincronizado_em: null,
    criado_em: iso(-2),
    atualizado_em: agora,
  },
];

const conversas = [
  {
    id: id(501),
    wa_chat_id: "5511987654321",
    telefone: "11987654321",
    nome_whatsapp: "Ana Exemplo",
    foto_url: null,
    contato_id: id(101),
    status: "aberta",
    ultimo_em: iso(0, 11),
    ultima_msg: "Perfeito, pode mandar o convite da demo.",
    nao_lidas: 1,
    eh_grupo: false,
    fixada: true,
    nao_lida_manual: false,
    canal: "whatsapp",
    chatwoot_conversation_id: null,
    chatwoot_inbox_id: null,
    chatwoot_contact_id: null,
    instagram_username: null,
    criado_em: iso(-8),
    atualizado_em: agora,
  },
  {
    id: id(502),
    wa_chat_id: "5511966554433",
    telefone: "11966554433",
    nome_whatsapp: "Elisa Exemplo",
    foto_url: null,
    contato_id: id(105),
    status: "aberta",
    ultimo_em: iso(-1, 18),
    ultima_msg: "Vi o formulário no site e quero entender o plano.",
    nao_lidas: 0,
    eh_grupo: false,
    fixada: false,
    nao_lida_manual: false,
    canal: "whatsapp",
    chatwoot_conversation_id: null,
    chatwoot_inbox_id: null,
    chatwoot_contact_id: null,
    instagram_username: null,
    criado_em: iso(-2),
    atualizado_em: agora,
  },
];

const mensagens = [
  {
    id: id(601),
    conversa_id: id(501),
    wa_message_id: null,
    direcao: "in",
    corpo: "Oi! Conseguimos marcar a demo esta semana?",
    tipo: "text",
    media_url: null,
    media_mime: null,
    media_nome: null,
    status: "delivered",
    autor_id: null,
    autor_email: null,
    chatwoot_message_id: null,
    criado_em: iso(-1, 10),
  },
  {
    id: id(602),
    conversa_id: id(501),
    wa_message_id: null,
    direcao: "out",
    corpo: "Claro. Quinta às 14h funciona?",
    tipo: "text",
    media_url: null,
    media_mime: null,
    media_nome: null,
    status: "read",
    autor_id: id(1),
    autor_email: "preview@crm.local",
    chatwoot_message_id: null,
    criado_em: iso(-1, 10),
  },
  {
    id: id(603),
    conversa_id: id(501),
    wa_message_id: null,
    direcao: "in",
    corpo: "Perfeito, pode mandar o convite da demo.",
    tipo: "text",
    media_url: null,
    media_mime: null,
    media_nome: null,
    status: "delivered",
    autor_id: null,
    autor_email: null,
    chatwoot_message_id: null,
    criado_em: iso(0, 11),
  },
  {
    id: id(604),
    conversa_id: id(502),
    wa_message_id: null,
    direcao: "in",
    corpo: "Vi o formulário no site e quero entender o plano.",
    tipo: "text",
    media_url: null,
    media_mime: null,
    media_nome: null,
    status: "delivered",
    autor_id: null,
    autor_email: null,
    chatwoot_message_id: null,
    criado_em: iso(-1, 18),
  },
];

export function createPreviewDb(): PreviewDb {
  return {
    etapas: etapas.map((r) => ({ ...r })),
    contatos: contatos.map((r) => ({ ...r })),
    oportunidades: oportunidades.map((r) => ({ ...r })),
    etiquetas: etiquetas.map((r) => ({ ...r })),
    contato_etiquetas: contato_etiquetas.map((r) => ({ ...r })),
    tarefas: tarefas.map((r) => ({ ...r })),
    calendario_eventos: calendario_eventos.map((r) => ({ ...r })),
    conversas: conversas.map((r) => ({ ...r })),
    mensagens: mensagens.map((r) => ({ ...r })),
    user_roles: [],
    profiles: [],
    oportunidade_comentarios: [],
    audit_logs: [],
    entradas_log: [],
    google_credentials: [],
    pausar_ia: [],
    dados_conversa: [],
    gpt_conversas: [],
    gpt_mensagens: [],
  };
}
